### ISSUE TITLE
Global "AudioWorkletGlobalScope " has leading or trailing whitespace

### ISSUE THREAD

**Issue by gersongoulart** [sindresorhus/globals#244]
While attempting to upgrade the `.eslintrc` to the new `eslint.config.js` flat format, ESLint is throwing the following error:

```
Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Key "languageOptions": Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace.
    at ObjectSchema.validate (node_modules/@humanwhocodes/object-schema/src/object-schema.js:287:23)
    at node_modules/@humanwhocodes/object-schema/src/object-schema.js:239:18
    at Array.reduce (<anonymous>)
    at ObjectSchema.merge (node_modules/@humanwhocodes/object-schema/src/object-schema.js:237:24)
    at node_modules/@humanwhocodes/config-array/api.js:935:42
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (node_modules/@humanwhocodes/config-array/api.js:934:39)
    at FlatConfigArray.isFileIgnored (node_modules/@humanwhocodes/config-array/api.js:962:15)
    at node_modules/eslint/lib/eslint/eslint-helpers.js:312:49
    at Array.reduce (<anonymous>)
```

**Comment by philsherry** [comment]
@gersongoulart Your ESLint config is most likely reading from an older `globals` package which something else just happened to put in your `node_modules`. Install it explicitly and you'll fix the problem.

The issue should really be mentioned over on the ESLint docs, where they neglect to mention actually installing the package.
