### ISSUE TITLE
AudioWorkletGlobalScope trailing white-space

### ISSUE THREAD

**Issue by MarsHeer** [sindresorhus/globals#265]
Eslint throwing the following error coming from a trailling white-space in the `AudioWorkletGlobalScope` key

```
ESLint: 9.11.1

TypeError: Key "languageOptions": Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace.
    at new Config (/Users/user/desarrollo/project/node_modules/eslint/lib/config/config.js:211:23)
    at [finalizeConfig] (/Users/user/desarrollo/project/node_modules/eslint/lib/config/flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (/Users/user/desarrollo/project/node_modules/@eslint/config-array/dist/cjs/index.cjs:1102:55)
    at FlatConfigArray.getConfig (/Users/user/desarrollo/project/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at /Users/user/desarrollo/project/node_modules/eslint/lib/eslint/eslint-helpers.js:346:56
    at Array.reduce (<anonymous>)
    at /Users/user/desarrollo/project/node_modules/eslint/lib/eslint/eslint-helpers.js:333:36
    at /Users/user/desarrollo/project/node_modules/eslint/lib/eslint/eslint-helpers.js:296:32
    at Object.isAppliedFilter (/Users/user/desarrollo/project/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
    at AsyncReader._handleEntry (/Users/user/desarrollo/project/node_modules/@nodelib/fs.walk/out/readers/async.js:86:20)
```

![image](https://github.com/user-attachments/assets/ef68ad7d-b431-4c11-a6fe-feb6c4f56882)

**Comment by MarsHeer** [comment]
Just noticed I'm on v14. Closing issue
