### ISSUE TITLE
Spelling error on a key

### ISSUE THREAD

**Issue by kaogire** [sindresorhus/globals#269]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `globals@11.12.0` for the project I'm working on.

While doing a lib bump I encountered this error

```
Oops! Something went wrong! :(

ESLint: 9.13.0

TypeError: Key "languageOptions": Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace.
    at new Config (/Users/cutler/Documents/kazi/admin/node_modules/eslint/lib/config/config.js:215:19)
    at [finalizeConfig] (/Users/cutler/Documents/kazi/admin/node_modules/eslint/lib/config/flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (/Users/cutler/Documents/kazi/admin/node_modules/@eslint/config-array/dist/cjs/index.cjs:1102:55)
    at FlatConfigArray.getConfig (/Users/cutler/Documents/kazi/admin/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at entryFilter (/Users/cutler/Documents/kazi/admin/node_modules/eslint/lib/eslint/eslint-helpers.js:286:40)
    at async NodeHfs.<anonymous> (file:///Users/cutler/Documents/kazi/admin/node_modules/@humanfs/core/src/hfs.js:560:24)
    at async NodeHfs.<anonymous> (file:///Users/cutler/Documents/kazi/admin/node_modules/@humanfs/core/src/hfs.js:590:6)
    at async NodeHfs.<anonymous> (file:///Users/cutler/Documents/kazi/admin/node_modules/@humanfs/core/src/hfs.js:590:6)
    at async NodeHfs.<anonymous> (file:///Users/cutler/Documents/kazi/admin/node_modules/@humanfs/core/src/hfs.js:590:6)
    at async NodeHfs.walk (file:///Users/cutler/Documents/kazi/admin/node_modules/@humanfs/core/src/hfs.js:600:3)
error Command failed with exit code 2.
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/globals/globals.json b/node_modules/globals/globals.json
index 6f5ac02..296710a 100644
--- a/node_modules/globals/globals.json
+++ b/node_modules/globals/globals.json
@@ -252,7 +252,7 @@
 		"AudioParam": false,
 		"AudioProcessingEvent": false,
 		"AudioScheduledSourceNode": false,
-		"AudioWorkletGlobalScope ": false,
+		"AudioWorkletGlobalScope": false,
 		"AudioWorkletNode": false,
 		"AudioWorkletProcessor": false,
 		"BarProp": false,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sindresorhus** [comment]
That's an old version of this package.

**Comment by jared-smith-kr** [comment]
@sindresorhus that's the version of this package pulled in by the version of babel used by the vite react plugin, and a lot of people using it and migrating to the new eslint flat config are going to hit this error (which is how I got here). I realize there are plenty of ways to fix this and it's not your problem, but you may be doing yourself a favor forestalling some duplicate issues by adding a quick note in the README. Your call of course.
